; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=RV64I

define i64 @test6(i64 %x) {
  %a = and i64 %x, 3221225472
  %b = shl i64 %a, 1
  ret i64 %b
}